-- ==========================================
-- Supabase SQL setup for private "message yourself" chat
-- Run this in Supabase SQL Editor once
-- ==========================================

-- Create messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  username text not null,
  text text not null,
  created_at timestamptz not null default now()
);

-- Helpful index for per-user reads
create index if not exists idx_messages_user_created
  on public.messages (user_id, created_at);

-- Enable row level security
alter table public.messages enable row level security;

-- Users can read only their own rows
create policy "Users read own messages"
on public.messages
for select
using (auth.uid() = user_id);

-- Users can insert only their own rows
create policy "Users insert own messages"
on public.messages
for insert
with check (auth.uid() = user_id);
